---

- name:Install and start nginx
  hosts:all
  become: root

  tasks:
    -name: Insatll nginx
     apt:
        name:nginx
        state:present

    -name: Start nginx
     service:  
        name:nginx
        state:started
